"""add session management

Revision ID: 153c258211ac
Revises: 24aa5aeafcbd
Create Date: 2026-07-01 21:43:02.281780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '153c258211ac'
down_revision: Union[str, Sequence[str], None] = '24aa5aeafcbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arma_session_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('has_coop_ended', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('arma_session_messages')
    # ### end Alembic commands ###
