"""mission forum thread

Revision ID: 24aa5aeafcbd
Revises: 7e0f11c7dd92
Create Date: 2026-04-09 19:39:40.067314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24aa5aeafcbd'
down_revision: Union[str, Sequence[str], None] = '7e0f11c7dd92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mission_forums',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.BigInteger(), nullable=False),
    sa.Column('mission_uuid', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mission_uuid'),
    sa.UniqueConstraint('thread_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mission_forums')
    # ### end Alembic commands ###
